
class categories ():

    Communication_Sub = [
                'Meaningful names: give variables, methods, classes, and packages non-abbreviated, intention-revealing names',
                'No magic values: use constants for all values used multiple times or in program logic',
                'Write readable code instead of comments: use comments only to explain important design decisions or purpose of code, not to restate code logic',
                'Use scope wisely: variables should be declared as close as possible to where they are used',
                'At all points, code should be "at the same level" (try not to mix method calls and low-level if logic in same method)',
                'Code should be "concise" (use booleans wisely, for-each loop where possible, use Java API calls instead of implementing yourself)',
                'Code should contain no warnings from Java compiler or CheckStyle']

    Modularbility_sub = [
                "Tell, don't ask: classes should be responsible for their own data and delegate to other objects instead of doing it themselves",
                "No public instance variables: keep implementation details of your class hidden from the public interface",
                'No "manager" classes: create several classes that work together distributing intelligence, rather than one "smart" class and a few "dumb" helpers',
                'No static variables: there should be no reason for shared global public state',
                'Active classes: classes should not consist of only get/set methods and, in general, should minimize their use. ',
                'get methods should give away the minimal information possible',
                'set methods should validate data received',
                'Superclasses are their own class: thus should not contain instance variables or methods specific to only some subclasses']

    Flexibility_sub = [
                'DRY: no duplicated code, either exactly (from cutting and pasting), structurally (in flow of control or decisions), or in setup ("boilerplate" code)',
                'Declared types should be as general as possible (i.e., ArrayList should never be visible in your public interface)',
                'Single Purpose: keep classes, methods, and variables short and well named by giving them only one purpose',
                'Behavior Driven Design: give each class a purpose by focusing on the behavior (or services) it provides first, its state later',
                'Polymorphism: use subclassing to avoid "case-based code logic" (i.e., conditional chains or case statements on "type" information)']



    rules = {'squid:S1942' : ['communication',1],
             'squid:S00115' : ['communication',1],
             'squid:S1223' : ['communication',1],
             'squid:S1190' : ['communication',1],
             'squid:S1221' : ['communication',1],
             'squid:S00101' : ['communication',1],
             'squid:S1700' : ['communication',1],
             'squid:S109' : ['communication', 2],
             'squid:S00122': ['communicaion', 3],
             'squid:S00121': ['communicaion', 3],
             'squid:S2681': ['communicaion', 3],
             'squid:S1941' : ['communicaion', 4],
             'squid:S881': ['communicaion', 5],
             'squid:S2114': ['communicaion', 5],
             'squid:S1604': ['communication', 6],
             'squid:S2175': ['communication', 6],
             'squid:S1126': ['communication', 6],
             'squid:S2293': ['communication', 6],
             'squid:S2200': ['communication', 6],
             'squid:S2589': ['communication', 6],
             'squid:S1871': ['communication', 6],
             'squid:S1656': ['communication', 6],
             'squid:S2178': ['communication', 6],
             'squid:S2959': ['communication', 6],
             'squid:S2185': ['communication', 6],
             'squid:S1192': ['communication', 6],
             'squid:S3923': ['communication', 6],
             'squid:S1481': ['communication', 6],
             'squid:S1125': ['communication', 6],
             'squid:S2147': ['communication', 7],
             'squid:S1157': ['communication', 7],
             'squid:UselessParenthesesCheck': ['communication', 7],
             'squid:S1488': ['communication', 7],
             'squid:S1764': ['communication', 7],
             'squid:S00108': ['communication', 7],
             'squid:S2153': ['communication', 7],
             'squid:S1170': ['communication', 7],
             'squid:S1133': ['communication', 7],
             'squid:S2097': ['communication', 7],
             'squid:S2154': ['communication', 7],
             'squid:S1199': ['communication', 7],
             'squid:UselessImportCheck': ['communication', 7],
             'squid:S2159': ['communication', 7],
             'squid:S135': ['communication', 7],
             'squid:S2692': ['communication', 7],
             'squid:S1710': ['communication', 7],
             'squid:S1066': ['communication', 7],
             'squid:S1068': ['communication', 7],
             'squid:S00112': ['communication', 7],
             'squid:S1148': ['communication', 7],
             'squid:S1244': ['communication', 7],
             'squid:S3358': ['communication', 7],
             'squid:S2208': ['communication', 7],
             'squid:S1450': ['modularity', 1],
             'squid:S1258': ['modularity', 1],
             'squid:HiddenFieldCheck': ['modularity', 1],
             'squid:S3066': ['modularity', 2],
             'squid:ClassVariableVisibilityCheck' : ['modularity', 2],
             'squid:S00104': ['modularity', 3],
             'squid:S1200': ['modularity', 3],
             'squid:S1188': ['modularity', 3],
             'squid:S1448': ['modularity', 3],
             'squid:S2786': ['modularity', 4],
             'squid:S2390': ['modularity', 4],
             'squid:S2386': ['modularity', 4],
             'squid:S2885': ['modularity', 4],
             'squid:S2209': ['modularity', 4],
             'squid:S1444': ['modularity', 4],
             'squid:S1185' : ['modularity', 7],
             'squid:S2638' : ['modularity', 7],
             'common - java:DuplicatedBlocks' : ['flexibility', 1],
             'squid:S3047' : ['flexibility', 1],
             'squid:S1939' : ['flexibility', 1],
             'squid:S1319' : ['flexibility', 2],
             'squid:S138': ['flexibility', 3],
             'squid:S1067': ['flexibility', 3],
             'squid:MethodCyclomaticComplexity': ['flexibility', 3],
             'squid:S00107': ['flexibility', 3],
             'squid:S3776': ['flexibility', 3],
             'squid:S2176': ['flexibility', 3],
             'squid:S3400' : ['flexibility', 4],
             'squid:S1479' : ['flexibility', 5],
             'squid:S1219' : ['flexibility', 5],
             'squid:S1151' : ['flexibility', 5],
             'squid:S1181': ['javanote'],
             'squid:S2129': ['javanote'],
             'squid:S2141': ['javanote'],
             'squid:S1872': ['javanote'],
             'squid:S1641': ['javanote'],
             'squid:S1640': ['javanote'],
             'squid:S1643': ['javanote'],
             'squid:S1850': ['javanote'],
             'squid:S2275': ['javanote'],
             'squid:S2864': ['javanote'],
             'squid:S1186': ['javanote'],
             'squid:S1858': ['javanote'],
             'squid:CallToDeprecatedMethod': ['javanote'],
             'squid:S1150': ['javanote'],
             'squid:EmptyFile': ['javanote'],
             'squid:S2694': ['javanote'],
             'squid:S1155': ['javanote'],
             'squid:S1213': ['javanote'],
             'squid:S1210': ['javanote'],
             'squid:S1158': ['javanote'],
             'squid:S3631': ['javanote'],
             'squid:S2789': ['javanote'],
             'squid:S3457': ['javanote'],
             'squid:S2094': ['javanote'],
             'squid:ObjectFinalizeOverridenCallsSuperFinalizeCheck': ['javanote'],
             'squid:S2177': ['javanote'],
             'squid:S1118': ['javanote'],
             'squid:S2133': ['javanote'],
             'squid:S2156': ['javanote'],
             'squid:S2131': ['javanote'],
             'squid:S1194': ['javanote'],
             'squid:S1197': ['javanote'],
             'squid:S1695': ['javanote'],
             'squid:S2975': ['javanote'],
             'squid:S2972': ['javanote'],
             'squid:S1596': ['javanote'],
             'squid:S2696': ['javanote'],
             'squid:S1610': ['javanote'],
             'squid:S1611': ['javanote'],
             'squid:S1698': ['javanote'],
             'squid:S1711': ['javanote'],
             'squid:S1201': ['javanote'],
             'squid:S1168': ['javanote'],
             'squid:S2384': ['javanote'],
             'squid:S2387': ['javanote'],
             'squid:S1228': ['javanote'],
             'squid:S3038': ['javanote'],
             'squid:S1165': ['javanote'],
             'squid:S2440': ['javanote'],
             'squid:S1206': ['javanote'],
             'squid:S1160': ['javanote'],
             'squid:S3422': ['javanote'],
             'squid:S2388': ['javanote'],
             'squid:S2301': ['javanote'],
             'squid:S2160': ['javanote'],
             'squid:UndocumentedApi': ['javanote'],
             'squid:S2162': ['javanote'],
             'squid:S1166': ['javanote'],
             'squid:S2166': ['javanote'],
             'squid:S1994': ['codesmell'],
             'squid:S1226': ['codesmell'],
             'squid:S1862': ['codesmell'],
             'squid:S2252': ['codesmell'],
             'squid:S2251': ['codesmell'],
             'squid:S134': ['codesmell'],
             'squid:IndentationCheck': ['codesmell'],
             'squid:S1905': ['codesmell'],
             'squid:S2189': ['codesmell'],
             'squid:ForLoopCounterChangedCheck': ['codesmell']
    }

    def getRules (self, rule):
        return self.rules[rule]